# Advanced Armor by iLucaH
# Please if you encounter any issues, report it
# Discord: https://discord.gg/GquPc7h
# Wiki: https://github.com/iLucaH/AdvancedArmor/wiki
# Config Info: https://github.com/iLucaH/AdvancedArmor/wiki/Documented-config

Money-Armor:
  Economy-Dependencies:
    Essentials-Enabled: false
    ShopGUIPlus-Enabled: false
    UltraPrisonCore-Enabled: false
    UltraBackpacks-Enabled: false
    ClipAutoSell-Enabled: false
    DeluxeSellWands-Enabled: false
    InfiniteChestPro:
      Enabled: false
      HookType: 'Essentials'
Coin-Armor:
  Economy-Dependencies:
    SuperMobCoins-Enabled: false
    KrakenMobCoins-Enabled: false
    TheOnlyMobCoins-Enabled: false
    QuadrexMobCoins-Enabled: false
    TMMobcoins-Enabled: false
    AquaCoins-Enabled: false
Token-Armor:
  Economy-Dependencies:
    UltraPrisonCore-Enabled: false
    DeluxeSellWands-Enabled: false
Gem-Armor:
  Economy-Dependencies:
    UltraPrisonCore-Enabled: false

Armor:
  Types:
    Fire:
      Name: '<GRADIENT:FF4200>&lFire %armor_type%</GRADIENT:FFC800>'
      ArmorColor: 'ORANGE'
      Lore:
        - '&4&l * <SOLID:FFDC00>Experience Boost Armor'
        - '&r'
        - '&4&l * <SOLID:FFC800>1 Piece: 15% EXP Boost'
        - '&4&l * <SOLID:FFBD00>2 Piece: 30% EXP Boost'
        - '&4&l * <SOLID:FFAA00>3 Piece: 45% EXP Boost'
        - '&4&l * <SOLID:FF9E00>4 Piece: 60% EXP Boost'
      Enchants:
        Unbreaking: 10
        Protection: 10
        Fireprotection: 10
      Flags:
        Unbreakable: false
        HIDE_UNBREAKABLE: false
        HIDE_ATTRIBUTES: false
        HIDE_ENCHANTS: false
      Boost:
        Type: 'EXP'
        Helmet-Percentage: 15
        Chestplate-Percentage: 15
        Leggings-Percentage: 15
        Boots-Percentage: 15
    PiggyBank:
      Name: '<GRADIENT:00F9FF>&lPiggyBank %armor_type%</GRADIENT:2D8789>'
      ArmorColor: 'AQUABLUE'
      Lore:
        - '&b&l * <SOLID:00F9FF>Money Boost Armor'
        - '&r'
        - '&b&l * <SOLID:08D6DB>1 Piece: 15% Money Boost'
        - '&b&l * <SOLID:06B3B7>2 Piece: 30% Money Boost'
        - '&b&l * <SOLID:078D90>3 Piece: 45% Money Boost'
        - '&b&l * <SOLID:066D6F>4 Piece: 60% Money Boost'
      Enchants:
        Unbreaking: 10
        Protection: 10
      Flags:
        Unbreakable: false
        HIDE_UNBREAKABLE: false
        HIDE_ATTRIBUTES: false
        HIDE_ENCHANTS: false
      Boost:
        Type: 'MONEY'
        Helmet-Percentage: 15
        Chestplate-Percentage: 15
        Leggings-Percentage: 15
        Boots-Percentage: 15
    Coin:
      Name: '&6&lCoin &e&l%armor_type%'
      ArmorColor: 'GOLD'
      Lore:
        - '&6&l * &eMobCoin Boost Armor'
        - '&r'
        - '&6&l * &eHelmet Piece: &f&n10% Mobcoin Boost'
        - '&6&l * &eChestplate Piece: &f&n20% Mobcoin Boost'
        - '&6&l * &eLeggings Piece: &f&n30% Mobcoin Boost'
        - '&6&l * &eBoots Piece: &f&n40% Mobcoin Boost'
      Enchants:
        Unbreaking: 10
        Protection: 10
      Flags:
        Unbreakable: false
        HIDE_UNBREAKABLE: false
        HIDE_ATTRIBUTES: false
        HIDE_ENCHANTS: false
      Boost:
        Type: 'COIN'
        Helmet-Percentage: 10
        Chestplate-Percentage: 20
        Leggings-Percentage: 30
        Boots-Percentage: 40
    Sunkist:
      Name: '<GRADIENT:F4FF00>&lSunkist %armor_type%</GRADIENT:FF7400>'
      ArmorColor: 'ORANGE'
      Lore:
        - '<GRADIENT:F4FF00> * Token Boost Armor</GRADIENT:FF7400>'
        - '&r'
        - '<GRADIENT:F4FF00> * 1 Piece: 30% Money Boost</GRADIENT:FF7400>'
        - '<GRADIENT:F4FF00> * 2 Piece: 60% Money Boost</GRADIENT:FF7400>'
        - '<GRADIENT:F4FF00> * 3 Piece: 90% Money Boost</GRADIENT:FF7400>'
        - '<GRADIENT:F4FF00> * 4 Piece: 120% Money Boost</GRADIENT:FF7400>'
      Enchants:
        Unbreaking: 10
        Protection: 10
      Flags:
        Unbreakable: true
        HIDE_UNBREAKABLE: false
        HIDE_ATTRIBUTES: false
        HIDE_ENCHANTS: false
      Boost:
        Type: 'TOKEN'
        Helmet-Percentage: 30
        Chestplate-Percentage: 30
        Leggings-Percentage: 30
        Boots-Percentage: 30
    Crystal:
      Name: '<GRADIENT:9B00FF>&lSunkist %armor_type%</GRADIENT:F1DAFF>'
      ArmorColor: 'HOTPINK'
      Lore:
        - '<GRADIENT:9B00FF> * Token Boost Armor</GRADIENT:F1DAFF>'
        - '&r'
        - '<GRADIENT:9B00FF> * 1 Piece: 50% Money Boost</GRADIENT:F1DAFF>'
        - '<GRADIENT:9B00FF> * 2 Piece: 100% Money Boost</GRADIENT:F1DAFF>'
        - '<GRADIENT:9B00FF> * 3 Piece: 150% Money Boost</GRADIENT:F1DAFF>'
        - '<GRADIENT:9B00FF> * 4 Piece: 200% Money Boost</GRADIENT:F1DAFF>'
      Enchants:
        Unbreaking: 10
        Protection: 10
      Flags:
        Unbreakable: true
        HIDE_UNBREAKABLE: false
        HIDE_ATTRIBUTES: false
        HIDE_ENCHANTS: false
      Boost:
        Type: 'GEM'
        Helmet-Percentage: 50
        Chestplate-Percentage: 50
        Leggings-Percentage: 50
        Boots-Percentage: 50

ArmorColor:
  RED:
    R: 255
    G: 0
    B: 0
  GREEN:
    R: 0
    G: 255
    B: 0
  BLUE:
    R: 0
    G: 0
    B: 255
  YELLOW:
    R: 255
    G: 243
    B: 0
  ORANGE:
    R: 255
    G: 135
    B: 0
  PINK:
    R: 255
    G: 115
    B: 225
  GRAY:
    R: 170
    G: 167
    B: 168
  HOTPINK: 
    R: 255
    G: 0
    B: 108
  LIGHTBLUE:
    R: 216
    G: 251
    B: 255
  PALEGREEN:
    R: 0
    G: 255
    B: 184
  LIME:
    R: 13
    G: 255
    B: 0
  AQUABLUE:  
    R: 0
    G: 255
    B: 218
  MAROON:
    R: 140
    G: 22
    B: 22
  GOLD:
    R: 255
    G: 215
    B: 0

Translations:
  Helmet: 'Helmet'
  Chestplate: 'Chestplate'
  Leggings: 'Leggings'
  Boots: 'Boots'
  Placeholders:
    No-Armor-Equipped: '&cNo Armor Equipped!'

Messages:
  Console-Name: 'Server'
  No-Permission:
    - '&cYou do not have permission to execute this command.'
  Armor-Correct-Usage:
    - '&cCorrect Usage:'
    - '&c* &7/armor give <name> <armor_type> <piece> - Give someone an armor piece.'
    - '&c* &7/armor types - List the armor types.'
    - '&c* &7/armor reload - Reloads the config.'
  Command-Info:
    - '&b&l -= &7&l&nAdvanced Armor Commands: &b&l=-'
    - '&b&l* &7/armor give <name> <armor_type> <piece> - Give someone an armor piece.'
    - '&b&l* &7/armor types - List the armor types.'
    - '&b&l* &7/armor reload - Reloads the config.'
  Armor-Types-Message:
    - '&b&lHere are the armor types:'
  Incorrect-Type-Of-Piece:
    - '&cPlease enter a correct piece:'
    - '&7&oHELMET, CHESTPLATE, LEGGINGS, BOOTS'
  Incorrect-Armor-Type:
    - '&cPlease enter a correct armor type:'
  Player-Not-Online:
    - '&c{username} is not online.'
  Player-Does-Not-Exist:
    - '&c{username} does not exist.'
  Sent-Player-Armor-Message:
    - '&bYou sent {username} an {armor_type} {armor_piece}.'
  Received-Armor-Message:
    - '&bYou received an {armor_type} {armor_piece} from {username}'
  Reload-Failed:
    - '&cThere was an issue when reloading the config'
    - '%issue-printout%'
  Reload-Config:
    - '&aYou Reloaded The Config'
  BoostMessages:
    EXP:
      Enabled: false
      Message:
        - '&a&l+ %amount% Experience &7(EXP Armor)'
    Money:
      Enabled: true
      Message:
        - '&a&l+ $%amount% &7(Money Armor)'
    Coins:
      Enabled: true
      Message:
        - '&a&l+ %amount% &7(Coin Armor)'
    Tokens:
      Enabled: true
      Message:
        - '&e&l+ %amount% &7(Tokens Armor)'
    Gems:
      Enabled: true
      Message:
        - '&de&l+ %amount% &7(Gem Armor)'
Debug:
  Enabled: false
  Cosole: false
  Player: false