# Advanced Armor by iLucaH
# Please if you encounter any issues, report it
# Discord: https://discord.gg/GquPc7h
# Wiki: https://github.com/iLucaH/AdvancedArmor/wiki
# Config Info: https://github.com/iLucaH/AdvancedArmor/wiki/Documented-config

Money-Armor:
  Economy-Dependencies:
    Essentials-Enabled: false
    ShopGUIPlus-Enabled: false
    UltraPrisonCore-Enabled: false
    UltraBackpacks-Enabled: false
    ClipAutoSell-Enabled: false
    DeluxeSellWands-Enabled: false
    InfiniteChestPro:
      Enabled: false
      HookType: 'Essentials'
Coin-Armor:
  Economy-Dependencies:
    SuperMobCoins-Enabled: false
    KrakenMobCoins-Enabled: false
    TheOnlyMobCoins-Enabled: false
    QuadrexMobCoins-Enabled: false
    TMMobcoins-Enabled: false
    AquaCoins-Enabled: false
Token-Armor:
  Economy-Dependencies:
    UltraPrisonCore-Enabled: false
    DeluxeSellWands-Enabled: false
Gem-Armor:
  Economy-Dependencies:
    UltraPrisonCore-Enabled: false

Translations:
  Helmet: 'Helmet'
  Chestplate: 'Chestplate'
  Leggings: 'Leggings'
  Boots: 'Boots'
  Placeholders:
    No-Armor-Equipped: '&cNo Armor Equipped!'

Messages:
  Console-Name: 'Server'
  No-Permission:
    - '&cYou do not have permission to execute this command.'
  Armor-Correct-Usage:
    - '&cCorrect Usage:'
    - '&c* &7/armor give <name> <armor_type> <piece> - Give someone an armor piece.'
    - '&c* &7/armor types - List the armor types.'
    - '&c* &7/armor reload - Reloads the config.'
  Command-Info:
    - '&b&l -= &7&l&nAdvanced Armor Commands: &b&l=-'
    - '&b&l* &7/armor give <name> <armor_type> <piece> - Give someone an armor piece.'
    - '&b&l* &7/armor types - List the armor types.'
    - '&b&l* &7/armor reload - Reloads the config.'
  Armor-Types-Message:
    - '&b&lHere are the armor types:'
  Incorrect-Type-Of-Piece:
    - '&cPlease enter a correct piece:'
    - '&7&oHELMET, CHESTPLATE, LEGGINGS, BOOTS'
  Incorrect-Armor-Type:
    - '&cPlease enter a correct armor type:'
  Player-Not-Online:
    - '&c{username} is not online.'
  Player-Does-Not-Exist:
    - '&c{username} does not exist.'
  Sent-Player-Armor-Message:
    - '&bYou sent {username} an {armor_type} {armor_piece}.'
  Received-Armor-Message:
    - '&bYou received an {armor_type} {armor_piece} from {username}'
  Reload-Failed:
    - '&cThere was an issue when reloading the config'
    - '%issue-printout%'
  Reload-Config:
    - '&aYou Reloaded The Config'
  BoostMessages:
    EXP:
      Enabled: false
      Message:
        - '&a&l+ %amount% Experience &7(EXP Armor)'
    Money:
      Enabled: true
      Message:
        - '&a&l+ $%amount% &7(Money Armor)'
    Coins:
      Enabled: true
      Message:
        - '&a&l+ %amount% &7(Coin Armor)'
    Tokens:
      Enabled: true
      Message:
        - '&e&l+ %amount% &7(Tokens Armor)'
    Gems:
      Enabled: true
      Message:
        - '&de&l+ %amount% &7(Gem Armor)'

# For developers.
Debug:
  Enabled: false
  Cosole: false
  Player: false